### ISSUE TITLE
[PE-D][Tester D] Add command does not work as per UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-4/tp#119]
The UG states that the fields `[your name]` `[your phone number]` and so on are optional, while only the tags such as `n/` and `p/` are required. However, when entering the add command, these fields are not optional.

![image.png](https://raw.githubusercontent.com/tyw2811/ped/main/files/a48ca58f-63ea-4604-8069-324c358a7f08.png)

![image.png](https://raw.githubusercontent.com/tyw2811/ped/main/files/d64e5081-682e-4e3b-b7ab-0623489c4a72.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tyw2811/ped#4

**Comment by rjkoh** [comment]
???? misinterprets UG
