### ISSUE TITLE
[PE-D][Tester A] Capitalisation of Module Prefix and Suffix

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-4/tp#120]
![image.png](https://raw.githubusercontent.com/craeyeons/ped/main/files/5972bfa6-eb1a-4410-b338-2a98b7f4cbdc.png)

I like the idea of capitalising module prefixes and suffixes for consistency. However, instead of forcefully forcing the user to input the module codes with capitalised prefix and suffix, I suppose you could process this easily while parsing the input using a capitalisation function of String in Java?

It's quite inconvenient to constantly hit the shift key to capitalise a few letters when the commands are all in lower case keys.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: craeyeons/ped#3

**Comment by rjkoh** [comment]
use .toUpperCase() instead
