### ISSUE TITLE
[PE-D][Tester D] Invalid module codes accepted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-4/tp#127]
It states in the UG that module codes must be registered modules in NUS, however, modules like `CS9901S` are accepted.

![image.png](https://raw.githubusercontent.com/tyw2811/ped/main/files/754256a5-0197-4b8c-adc1-a2b138609846.png)

![image.png](https://raw.githubusercontent.com/tyw2811/ped/main/files/a31b3f4e-5126-48c1-95d6-eae0fe5a6684.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tyw2811/ped#8

**Comment by rjkoh** [comment]
duplicate
