### ISSUE TITLE
[PE-D][Tester D] Command result after entering lesson unintuitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-4/tp#140]
The response by the app only states `Added lesson for Person...` whilst not stating who that person is. Would be nice to have either the name or index that the user had put in.

![image.png](https://raw.githubusercontent.com/tyw2811/ped/main/files/145ec989-d278-40da-8f72-92b38290b370.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: tyw2811/ped#12

**Comment by linuschui** [comment]
fixed
