### ISSUE TITLE
[PE-D][Tester A] Allows timetable clashes.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-4/tp#141]
![image.png](https://raw.githubusercontent.com/craeyeons/ped/main/files/514c33e3-fb6a-4406-b3eb-06f3538e54e4.png)

I am allowed to add two lessons of the same timing.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: craeyeons/ped#7

**Comment by linuschui** [comment]
fixed
