### ISSUE TITLE
[PE-D][Tester D] Entering the example remove command does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-4/tp#145]
Entering the example `remove` command given by the app will be rejected by the app.

![image.png](https://raw.githubusercontent.com/tyw2811/ped/main/files/a2993967-970a-41ef-8a48-65a4dc77e486.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tyw2811/ped#13

**Comment by rjkoh** [comment]
duplicate
