### ISSUE TITLE
[PE-D][Tester C] Syntax for "delete" in User Guide doesn't match actual command syntax

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T14-4/tp#147]
The User Guide states that `day/` is the tag used to specify the day of the lesson, but this doesn't work in the app and `d/` works.

![image.png](https://raw.githubusercontent.com/kaij77/ped/main/files/c4df2fc2-592b-4c7d-bbc0-8f0eeafc0bf0.png)

![image.png](https://raw.githubusercontent.com/kaij77/ped/main/files/92c8d63d-f0a7-4527-869a-a6a670d8827a.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: kaij77/ped#4

**Comment by rjkoh** [comment]
duplicate
